name: map_level_maker
description: Generate `MapLevel` class code.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  backstreets_widgets: ^0.6.0
  cupertino_icons: ^1.0.2
  dart_sdl: ^0.10.1
  dart_style: ^2.2.4
  dart_synthizer: ^0.11.1
  file: ^6.1.4
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  jinja: ^0.4.0-dev.51
  json_annotation: ^4.7.0
  path: ^1.8.2
  recase: ^4.1.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  ziggurat: ^0.54.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
